name: Deploy reminder

on:
  pull_request:
    types: [synchronize]

jobs:
  detect-wednesday:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check merge status
        if: ${{ github.event.pull_request.merged }} == 'true'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          # Get the current day of the week (0 = Sunday, 1 = Monday, ..., 6 = Saturday)
          day_of_week=$(date -u +'%w')
          if [ "$day_of_week" -eq 5 ]; then
            MESSAGE="Today is Friday!"
          else
            MESSAGE="Today is not Friday!"
          fi
          # Use the Octokit library to create a comment on the PR to ping the author
          import octokit from '@octokit/core'
          client = octokit.rest.createClient({
            auth: 'bearer ${{ secrets.NEW_PAT_TOKEN }}'
          })
          client.issues.createComment({
            issue_number: PR_NUMBER,
            body: MESSAGE,
            github_actor: 'github-actions[bot]'
          })
