name: Deploy reminder

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  detect-wednesday:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check merge status
        if: ${{ github.event.pull_request.merged }} == 'false'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          if [ "$day_of_week" -eq 5 ]; then
            MESSAGE="Hey @PR_AUTHOR, thanks for merging your PR! Please deploy it on Monday unless it's critical."
          else
            MESSAGE="Hey @$PR_AUTHOR, thanks for merging your PR! Don't forget to deploy it by following [these steps](https://github.com/Automattic/woocommerce-payments-server/#deploying)."
          fi
          # Use the GitHub API to create a comment on the PR to ping the author
          uses: peter-evans/create-or-update-comment@v3
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: $MESSAGE
            comment-author: 'github-actions[bot]'
