name: Mergeability Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_mergeable_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Mergeable Status
        id: check_mergeable
        run: echo "::set-output name=is_mergeable::${{ github.event.pull_request.mergeable }}"

      # Add your desired actions based on the mergeable status.
      # For example, you can use conditionals to perform different actions.
      - name: Merge PR Automatically
        if: steps.check_mergeable.outputs.is_mergeable == 'true'
        run: echo "Merging the pull request"

      - name: Notify Team
        if: steps.check_mergeable.outputs.is_mergeable == 'false'
        run: echo "The pull request has conflicts and needs manual attention."
