name: Mergeability Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_mergeability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Mergeability
        id: check_mergeable
        run: |
          # Use GitHub API to get the PR details and check mergeable status
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_MERGEABLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
                         | jq '.mergeable')
          echo "::set-output name=is_mergeable::$PR_MERGEABLE"

      - name: Print Mergeability Status
        run: echo "Is PR mergeable? ${{ steps.check_mergeable.outputs.is_mergeable }}"
