name: Check Mergeable Status
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_mergeable_status:
    runs-on: ubuntu-latest
    steps:
      - name: Before checking
        run: echo "Before checking"

      - name: Check mergeable status
        if: github.event.pull_request.mergeable
        run: echo "PR is mergeable"

      - name: After checking
        run: echo "After checking"
